import "server-only";
import { AsyncLocalStorage } from "node:async_hooks";
import fs from "node:fs";
import path from "node:path";
import { seedDemoVenues } from "./seed";

/**
 * PostgreSQL, through one small interface the repositories use.
 *
 * - With DATABASE_URL set (Supabase, Neon, RDS or your own server) it
 *   connects with `pg`. Moving between hosts is a change of that URL.
 * - Without it (local development, tests) it runs PGlite: real Postgres,
 *   embedded, saved under DATA_DIR/pg. Same SQL either way.
 *
 * Queries use `?` placeholders (turned into $1, $2…). Timestamps come back
 * as ISO strings in UTC ("2026-10-09T13:05:00.000Z") and counts as numbers,
 * so callers read rows the same whatever the driver.
 */

export const DATA_DIR = process.env.DATA_DIR || path.join(process.cwd(), "data");

export interface Db {
  all<T>(sql: string, ...params: unknown[]): Promise<T[]>;
  get<T>(sql: string, ...params: unknown[]): Promise<T | undefined>;
  /** Insert, update or delete; `changes` is the number of rows touched. */
  run(sql: string, ...params: unknown[]): Promise<{ changes: number }>;
  /** Several statements at once, without parameters (migrations). */
  exec(sql: string): Promise<void>;
}

const MIGRATIONS: string[] = [
  `CREATE TABLE venues (
     id TEXT PRIMARY KEY,
     short_code TEXT NOT NULL UNIQUE,
     config TEXT NOT NULL,
     status TEXT NOT NULL DEFAULT 'active',
     settings TEXT,
     previous_config TEXT,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
     updated_at TIMESTAMPTZ
   );
   CREATE TABLE customers (
     id TEXT PRIMARY KEY,
     venue_id TEXT NOT NULL REFERENCES venues(id),
     email TEXT NOT NULL,
     first_name TEXT,
     name TEXT,
     locale TEXT,
     capture_source TEXT,
     marketing_consent TEXT NOT NULL DEFAULT 'unasked',
     age_attested INTEGER NOT NULL DEFAULT 0,
     consent_token TEXT,
     consent_updated_at TIMESTAMPTZ,
     birthday_month INTEGER,
     birthday_day INTEGER,
     birthday_skips INTEGER NOT NULL DEFAULT 0,
     unsubscribe_token TEXT UNIQUE,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
     UNIQUE (venue_id, email)
   );
   CREATE TABLE loyalty_cards (
     id TEXT PRIMARY KEY,
     venue_id TEXT NOT NULL REFERENCES venues(id),
     customer_id TEXT NOT NULL UNIQUE REFERENCES customers(id),
     access_token TEXT NOT NULL,
     stamps INTEGER NOT NULL DEFAULT 0,
     last_pass_email_at TIMESTAMPTZ,
     last_feedback_stamp_at TIMESTAMPTZ,
     referral_code TEXT UNIQUE,
     referred_by_card_id TEXT,
     referral_rewarded_at TIMESTAMPTZ,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   CREATE TABLE visits (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     venue_id TEXT NOT NULL,
     customer_id TEXT NOT NULL,
     type TEXT NOT NULL,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   CREATE INDEX visits_venue ON visits(venue_id, created_at);
   CREATE TABLE feedback (
     id TEXT PRIMARY KEY,
     venue_id TEXT NOT NULL REFERENCES venues(id),
     text TEXT NOT NULL,
     sentiment DOUBLE PRECISION NOT NULL,
     source TEXT,
     image_path TEXT,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   CREATE INDEX feedback_venue ON feedback(venue_id, created_at);
   CREATE TABLE outbox (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     recipient TEXT NOT NULL,
     subject TEXT NOT NULL,
     body TEXT NOT NULL,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   CREATE TABLE events (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name TEXT NOT NULL,
     params JSONB,
     venue_id TEXT,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   CREATE INDEX events_venue ON events(venue_id, name, created_at);
   CREATE TABLE users (
     id TEXT PRIMARY KEY,
     email TEXT NOT NULL UNIQUE,
     name TEXT NOT NULL,
     password_hash TEXT NOT NULL,
     email_verified_at TIMESTAMPTZ,
     blocked_at TIMESTAMPTZ,
     is_admin INTEGER NOT NULL DEFAULT 0,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   CREATE TABLE sessions (
     id TEXT PRIMARY KEY,
     user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
     expires_at TIMESTAMPTZ NOT NULL,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   CREATE INDEX sessions_user ON sessions(user_id);
   CREATE TABLE auth_tokens (
     id TEXT PRIMARY KEY,
     user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
     purpose TEXT NOT NULL,
     expires_at TIMESTAMPTZ NOT NULL,
     used_at TIMESTAMPTZ
   );
   CREATE TABLE venue_members (
     venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
     user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
     role TEXT NOT NULL DEFAULT 'owner',
     feedback_seen_at TIMESTAMPTZ,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
     PRIMARY KEY (venue_id, user_id)
   );
   CREATE INDEX venue_members_user ON venue_members(user_id);
   CREATE TABLE subscriptions (
     venue_id TEXT PRIMARY KEY REFERENCES venues(id) ON DELETE CASCADE,
     plan TEXT NOT NULL DEFAULT 'free',
     status TEXT NOT NULL DEFAULT 'active',
     trial_ends_at TIMESTAMPTZ,
     current_period_end TIMESTAMPTZ,
     cancel_at_period_end INTEGER NOT NULL DEFAULT 0,
     provider TEXT,
     provider_customer_id TEXT,
     provider_subscription_id TEXT,
     updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   CREATE TABLE stamp_events (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     venue_id TEXT NOT NULL,
     card_id TEXT NOT NULL,
     kind TEXT NOT NULL,
     delta INTEGER NOT NULL,
     reward_name TEXT,
     device_id TEXT,
     undone_at TIMESTAMPTZ,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   CREATE INDEX stamp_events_card ON stamp_events(card_id, created_at);
   CREATE INDEX stamp_events_venue ON stamp_events(venue_id, kind, created_at);
   CREATE TABLE staff_devices (
     id TEXT PRIMARY KEY,
     venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
     label TEXT NOT NULL,
     user_id TEXT,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
     last_used_at TIMESTAMPTZ,
     revoked_at TIMESTAMPTZ
   );
   CREATE INDEX staff_devices_venue ON staff_devices(venue_id);
   CREATE TABLE staff_pairings (
     id TEXT PRIMARY KEY,
     venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
     label TEXT NOT NULL,
     user_id TEXT,
     expires_at TIMESTAMPTZ NOT NULL,
     used_at TIMESTAMPTZ
   );
   CREATE TABLE notification_prefs (
     user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
     venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
     weekly_digest INTEGER NOT NULL DEFAULT 1,
     PRIMARY KEY (user_id, venue_id)
   );
   CREATE TABLE job_runs (
     job TEXT NOT NULL,
     key TEXT NOT NULL,
     ran_at TIMESTAMPTZ NOT NULL DEFAULT now(),
     PRIMARY KEY (job, key)
   );
   CREATE TABLE ai_usage (
     venue_id TEXT NOT NULL,
     day TEXT NOT NULL,
     units INTEGER NOT NULL DEFAULT 0,
     PRIMARY KEY (venue_id, day)
   );
   CREATE TABLE guest_emails (
     customer_id TEXT NOT NULL,
     kind TEXT NOT NULL,
     key TEXT NOT NULL,
     sent_at TIMESTAMPTZ NOT NULL DEFAULT now(),
     PRIMARY KEY (customer_id, kind, key)
   );
   CREATE TABLE staff_invites (
     id TEXT PRIMARY KEY,
     venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
     email TEXT NOT NULL,
     invited_by TEXT,
     expires_at TIMESTAMPTZ NOT NULL,
     used_at TIMESTAMPTZ,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   CREATE INDEX staff_invites_venue ON staff_invites(venue_id);
   CREATE TABLE admin_actions (
     id TEXT PRIMARY KEY,
     admin_id TEXT,
     admin_email TEXT NOT NULL,
     action TEXT NOT NULL,
     target_type TEXT NOT NULL,
     target_id TEXT NOT NULL,
     target_label TEXT,
     detail TEXT,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   CREATE INDEX admin_actions_created ON admin_actions(created_at);
   CREATE INDEX admin_actions_target ON admin_actions(target_type, target_id);
   CREATE TABLE admin_edit_grants (
     admin_id TEXT NOT NULL,
     venue_id TEXT NOT NULL,
     expires_at TIMESTAMPTZ NOT NULL,
     PRIMARY KEY (admin_id, venue_id)
   );`,
  // Row-level security on, with no policies: hosted Postgres that also serves a
  // REST API (Supabase's Data API) then exposes nothing through it. The app
  // connects as the tables' owner, which RLS doesn't restrict.
  `ALTER TABLE venues ENABLE ROW LEVEL SECURITY;
   ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
   ALTER TABLE loyalty_cards ENABLE ROW LEVEL SECURITY;
   ALTER TABLE visits ENABLE ROW LEVEL SECURITY;
   ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;
   ALTER TABLE outbox ENABLE ROW LEVEL SECURITY;
   ALTER TABLE events ENABLE ROW LEVEL SECURITY;
   ALTER TABLE users ENABLE ROW LEVEL SECURITY;
   ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
   ALTER TABLE auth_tokens ENABLE ROW LEVEL SECURITY;
   ALTER TABLE venue_members ENABLE ROW LEVEL SECURITY;
   ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
   ALTER TABLE stamp_events ENABLE ROW LEVEL SECURITY;
   ALTER TABLE staff_devices ENABLE ROW LEVEL SECURITY;
   ALTER TABLE staff_pairings ENABLE ROW LEVEL SECURITY;
   ALTER TABLE notification_prefs ENABLE ROW LEVEL SECURITY;
   ALTER TABLE job_runs ENABLE ROW LEVEL SECURITY;
   ALTER TABLE ai_usage ENABLE ROW LEVEL SECURITY;
   ALTER TABLE guest_emails ENABLE ROW LEVEL SECURITY;
   ALTER TABLE staff_invites ENABLE ROW LEVEL SECURITY;
   ALTER TABLE admin_actions ENABLE ROW LEVEL SECURITY;
   ALTER TABLE admin_edit_grants ENABLE ROW LEVEL SECURITY;
   ALTER TABLE schema_version ENABLE ROW LEVEL SECURITY;`,
  // Feedback stamps need a receipt from a real feedback post; old page codes
  // keep pointing at their venue (so printed QR codes never reach anyone
  // else); outbox rows record whether the provider accepted them; indexes
  // for the daily clean-up.
  `ALTER TABLE feedback ADD COLUMN stamp_token TEXT;
   ALTER TABLE feedback ADD COLUMN stamp_claimed_at TIMESTAMPTZ;
   CREATE TABLE retired_codes (
     code TEXT PRIMARY KEY,
     venue_id TEXT REFERENCES venues(id) ON DELETE SET NULL,
     retired_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   ALTER TABLE retired_codes ENABLE ROW LEVEL SECURITY;
   ALTER TABLE outbox ADD COLUMN status TEXT NOT NULL DEFAULT 'logged';
   CREATE INDEX outbox_created ON outbox(created_at);
   CREATE INDEX events_created ON events(created_at);
   CREATE INDEX sessions_expires ON sessions(expires_at);`,
  // Was: remove the demo venues (reverted the same day; the demos stay). Kept
  // as a no-op so later migrations keep their numbers.
  `SELECT 1;`,
  // The AI summary of a venue's recent feedback, kept until new feedback changes it.
  `CREATE TABLE feedback_summaries (
     venue_id TEXT PRIMARY KEY REFERENCES venues(id) ON DELETE CASCADE,
     fingerprint TEXT NOT NULL,
     summary JSONB NOT NULL,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   );
   ALTER TABLE feedback_summaries ENABLE ROW LEVEL SECURITY;`,
];

/** "2026-10-09 13:05:00.123+00" → "2026-10-09T13:05:00.123Z": ISO in UTC, so Date.parse reads it right anywhere. */
function utcTimestamp(value: string): string {
  const iso = value.replace(" ", "T").replace(/([+-]\d\d)$/, "$1:00");
  const date = new Date(iso);
  return Number.isNaN(date.getTime()) ? value : date.toISOString();
}

/** Type OIDs: int8, numeric, timestamptz, timestamp, date. */
const PARSERS: Record<number, (value: string) => unknown> = {
  20: (value) => Number(value),
  1700: (value) => Number(value),
  1184: utcTimestamp,
  1114: (value) => value.slice(0, 19),
  1082: (value) => value,
};

/** `?` → `$1, $2…`, skipping anything inside quotes. */
export function numberPlaceholders(sql: string): string {
  let n = 0;
  let out = "";
  let quote: string | null = null;
  for (const ch of sql) {
    if (quote) {
      if (ch === quote) quote = null;
      out += ch;
    } else if (ch === "'" || ch === '"') {
      quote = ch;
      out += ch;
    } else if (ch === "?") {
      out += `$${++n}`;
    } else {
      out += ch;
    }
  }
  return out;
}

/** Booleans are stored as 0/1 (as they were in SQLite); undefined means NULL. */
function normalise(params: unknown[]): unknown[] {
  return params.map((p) => (p === undefined ? null : typeof p === "boolean" ? (p ? 1 : 0) : p));
}

type Query = (sql: string, params: unknown[]) => Promise<{ rows: unknown[]; changes: number }>;

function wrap(query: Query, execMany: (sql: string) => Promise<void>): Db {
  return {
    async all<T>(sql: string, ...params: unknown[]) {
      return (await query(numberPlaceholders(sql), normalise(params))).rows as T[];
    },
    async get<T>(sql: string, ...params: unknown[]) {
      return (await query(numberPlaceholders(sql), normalise(params))).rows[0] as T | undefined;
    },
    async run(sql: string, ...params: unknown[]) {
      return { changes: (await query(numberPlaceholders(sql), normalise(params))).changes };
    },
    exec: execMany,
  };
}

interface Driver {
  db: Db;
  transaction<T>(fn: (tx: Db) => Promise<T>): Promise<T>;
  close(): Promise<void>;
}

/**
 * TLS for a hosted database. With the provider's CA certificate
 * (DATABASE_SSL_CA: the PEM text or a file path; Supabase: Project Settings
 * → Database → SSL certificate) or DATABASE_SSL=verify (a certificate public
 * CAs sign), the server's identity is checked. Without either the link is
 * still encrypted but unchecked, and startup warns about it in production.
 */
export function databaseSsl(url: string): false | { rejectUnauthorized: boolean; ca?: string } {
  if (process.env.DATABASE_SSL === "off" || /localhost|127\.0\.0\.1/.test(url)) return false;
  const ca = process.env.DATABASE_SSL_CA?.trim();
  if (ca) return { rejectUnauthorized: true, ca: ca.includes("BEGIN CERTIFICATE") ? ca.replaceAll("\\n", "\n") : fs.readFileSync(ca, "utf8") };
  return { rejectUnauthorized: process.env.DATABASE_SSL === "verify" };
}

async function pgDriver(url: string): Promise<Driver> {
  const pg = (await import("pg")).default;
  const types = { getTypeParser: (oid: number, format?: string) => (PARSERS[oid] ? (PARSERS[oid] as (v: string) => unknown) : pg.types.getTypeParser(oid, format as "text")) };
  const pool = new pg.Pool({
    connectionString: url,
    max: Number(process.env.DATABASE_POOL_SIZE || 5),
    // Hosted Postgres (Supabase and most others) needs TLS; set DATABASE_SSL=off for a local server.
    ssl: databaseSsl(url) || undefined,
    types,
  });
  const onClient = (client: { query: (text: string, values?: unknown[]) => Promise<{ rows: unknown[]; rowCount: number | null }> }): Db =>
    wrap(
      async (sql, params) => {
        const result = await client.query(sql, params);
        return { rows: result.rows, changes: result.rowCount ?? 0 };
      },
      async (sql) => {
        await client.query(sql);
      },
    );
  return {
    db: onClient(pool),
    async transaction(fn) {
      const client = await pool.connect();
      try {
        await client.query("BEGIN");
        const result = await fn(onClient(client));
        await client.query("COMMIT");
        return result;
      } catch (error) {
        await client.query("ROLLBACK").catch(() => {});
        throw error;
      } finally {
        client.release();
      }
    },
    close: () => pool.end(),
  };
}

async function pgliteDriver(): Promise<Driver> {
  const { PGlite } = await import("@electric-sql/pglite");
  const dir = process.env.PGLITE_DIR || path.join(DATA_DIR, "pg");
  if (!dir.startsWith("memory://")) fs.mkdirSync(dir, { recursive: true });
  const lite = new PGlite(dir, { parsers: PARSERS });
  await lite.waitReady;
  type Runner = { query: (sql: string, params?: unknown[]) => Promise<{ rows: unknown[]; affectedRows?: number }>; exec: (sql: string) => Promise<unknown> };
  const onRunner = (runner: Runner): Db =>
    wrap(
      async (sql, params) => {
        const result = await runner.query(sql, params);
        return { rows: result.rows, changes: result.affectedRows ?? 0 };
      },
      async (sql) => {
        await runner.exec(sql);
      },
    );
  return {
    db: onRunner(lite),
    transaction: (fn) => lite.transaction((tx) => fn(onRunner(tx))),
    close: () => lite.close(),
  };
}

async function migrate(driver: Driver) {
  const { db } = driver;
  await db.exec("CREATE TABLE IF NOT EXISTS schema_version (version INTEGER NOT NULL)");
  const row = await db.get<{ version: number }>("SELECT version FROM schema_version");
  if (!row) await db.run("INSERT INTO schema_version (version) VALUES (0)");
  let version = row?.version ?? 0;
  while (version < MIGRATIONS.length) {
    const next = version + 1;
    await driver.transaction(async (tx) => {
      await tx.exec(MIGRATIONS[next - 1]);
      await tx.run("UPDATE schema_version SET version = ?", next);
    });
    version = next;
  }
}

declare global {
  // One connection (or pool) for the process, kept across dev hot reloads.
  var __appDriver: Promise<Driver> | undefined;
  var __appDriverMigrations: number | undefined;
}

async function open(): Promise<Driver> {
  const url = process.env.DATABASE_URL;
  const driver = url ? await pgDriver(url) : await pgliteDriver();
  await migrate(driver);
  await seedDemoVenues(driver.db);
  return driver;
}

function driver(): Promise<Driver> {
  // A hot reload can bring new migrations while the connection lives on.
  if (!globalThis.__appDriver || globalThis.__appDriverMigrations !== MIGRATIONS.length) {
    const previous = globalThis.__appDriver;
    globalThis.__appDriver = previous ? previous.then(async (d) => (await migrate(d), await seedDemoVenues(d.db), d)) : open();
    globalThis.__appDriverMigrations = MIGRATIONS.length;
    // A failed start (e.g. a wrong DATABASE_URL) is retried on the next request.
    globalThis.__appDriver.catch(() => {
      globalThis.__appDriver = undefined;
    });
  }
  return globalThis.__appDriver;
}

const activeTx = new AsyncLocalStorage<Db>();

/** The database: inside `transaction()`, the transaction's connection. */
export async function getDb(): Promise<Db> {
  return activeTx.getStore() ?? (await driver()).db;
}

/**
 * Runs `fn` in a transaction. Anything called inside it that uses getDb()
 * joins the same transaction, so repositories compose without passing it on.
 */
export async function transaction<T>(fn: (db: Db) => Promise<T>): Promise<T> {
  const current = activeTx.getStore();
  if (current) return fn(current);
  return (await driver()).transaction((tx) => activeTx.run(tx, () => fn(tx)));
}

/** Closes the connection; the next getDb() opens a fresh one. For tests and shutdown. */
export async function closeDb(): Promise<void> {
  const current = globalThis.__appDriver;
  globalThis.__appDriver = undefined;
  globalThis.__appDriverMigrations = undefined;
  if (current) await (await current).close();
}
